[build]
  command = "pnpm install && pnpm build --filter=@kzn-youth-choir/public-site"
  publish = "apps/public-site/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

